bascht/omemo-top

index.md

see https://www.jsxc.org/ for more informations

Add JavaScript XMPP Client (JSXC)

---

index.md

using a small non breakable space followed by subscript number to indicate library
(did I mention that I love my keyboard?)

use unicode subscript numbers instead of stars

---

index.md

I was not sure if irssi-xmpp is seen as a part of irssi or as an external library, so I added a footnote.

Added irssi to the list of clients

---

index.md

see https://github.com/jsxc/jsxc/issues/228#issuecomment-274081706

add WIP for JSXC

---

index.md

[lurch](https://github.com/gkdr/lurch) plugin for Pidgin seems to be already fully functional.
Please correct me if I edited list improperly.

Add Pidgin via lurch

---

_data/clients/pidgin.yml

I succesfully tested lurch with Gajim and conversations, so Pidgin is done! \o/

Lurch works

---

Gemfile.lock

Will hopefully fix the build (again)

Bump GitHub Pages + Jekyll Gem

---

_data/clients/implus.yml

(Thanks to Stefan Reutter for giving a hint.)

Add IM+ messenger

---

_data/clients/chatsecure.yml

ChatSecure is not 100%

---

_data/clients/zom.yml

https://github.com/zom/Zom-Android/issues/119

zom released

---

clients/boogie-chat

Added Boogie Chat
Unfortunately, I'm not sure if it's open source. Couldn't find a Github repo either....
https://twitter.com/boogie_chat

Create Boogie Chat

---

_config.yml
assets/css/style.scss
index.md

Add proper meta description & remove OTR shenanigans. #79

---

_data/clients/psi.yml
_data/clients/psi_plus.yml

Looks like Psi+ now [has a working plugin](https://github.com/psi-im/plugins/issues/10#issuecomment-361011306) for OMEMO. It's still WIP, though, but it's already a huge progress!
🎉

Update the progress of Psi+

---

_includes/client_row.html

@evaryont I've added some labels to the Emojis. 
wdyt?

Add emoji labels for clarification + probably a11y

---

_data/clients/miranda_ng.yml

Miranda supports Omemo now

---

_data/clients/swift.yml

So, if that changes, we still can change its status...

Swift does not really intend to work on OMEMO

---

_data/clients/psi.yml

see https://github.com/psi-im/psi/issues/252

carbons not yet supported

---

_data/clients/psi_plus.yml

see https://github.com/psi-im/psi/issues/252

carbons not supported yet

---

_data/clients/bitlbee.yml

This could raise awareness for bitlbees issues with the implementation.

Seems like somebody has opened a bountysource for this in 2017.

---

_data/clients/converse_js.yml

I hope this was done correctly.

Update Converse.js to show it has OMEMO support

---

_data/clients/sailfish_os.yml
_data/clients/shmoose.yml

Add SailfishOS clients

---

_data/clients/atalk.yml

Update aTalk omemo development status

aTalk status update

---

_data/clients/beagleim.yml

Code and issue tracker on https://tigase.tech/projects/beagle-im
Couldn't find a way to open an issue or a feature request, so I emailed them.

Add Beagle IM

---

_data/clients/slixmpp.yml

Not entirely sure how you want to use the progress bar. I just copied it from Sleekxmpp.
It is not released yet.
It supports:
- Decryption
- Encryption to any arbitrary number of JIDs. (1:1 and MUCs)
- Trust management (wrapper for the [omemo backend](https://github.com/syndace/python-omemo))
It doesn't yet support aesgcm.
I've been meaning to make a first alpha release for 2 weeks already. Any time now..
Signed-off-by: Maxime “pep” Buquet <pep@bouah.net>

Add slixmpp library

---

_data/clients/slixmpp.yml

Signed-off-by: Maxime “pep” Buquet <pep@bouah.net>

slixmpp: Change tracking issue to new repository

---

_data/clients/sleekxmpp.yml
_data/clients/slixmpp.yml
index.md

Fixes #154. I decided to move the libraries to their own section so that they aren't removed completely.

Move libraries to Libraries section

---

_data/clients/beagleim.yml
_data/clients/siskinim.yml
_data/clients/tigase-android-messenger.yml

Update:
* Beagle IM
Add
* Siskin IM
* Tigase Android Messenger

update Beagle IM data and add Siskin IM and Tigase Android Messenger

---

_data/clients/profanity.yml

First command line client DONE

---

_data/clients/uwpx.yml

Increased the UWPX progress from `63` to `84`.

Updated the UWPX progress

---

_data/clients/ConversationsIPv6.yml

Source: https://f-droid.org/en/packages/eu.sum7.conversations/

Update the name of "Conversations with IPv6"

---

_data/clients/implus.yml

Delete implus.yml as being a scam app

---

_data/clients/movim.yml

Add WIP support for Movim

---

_data/clients/monocles_chat.yml

(another nice conversations fork coming to f droid now

added monocles chat

---

_data/clients/SkrivaMe.yml

Remove discontinued Skriva

---

_data/clients/movim.yml

More info: https://mov.im/?node/pubsub.movim.eu/Movim/dd90cd1c-4bcd-45a5-88a3-220fd4280b21

Movim Skiff with OMEMO support is here

---

_data/clients/smuxi.yml

Added client Smuxi
