bascht/omemo-top

.gitignore, _data/clients/chatsecure.yml, _data/clients/conversations.yml, _data/clients/gajim.yml, _data/clients/jsxc.yml, _data/clients/movim.yml, _data/clients/pidgin.yml, _data/clients/profanity.yml, assets/css/style.scss, index.md
As i liked the design very much before, here is an alternative approach to initially sort by Done, Testing and WIP in sequence. Even it is a little "hacky", it maintains the nice design 😸
=> Design proposal ReneVolution

_data/clients/adium.yml
There is an Xtra packaging gkdr/lurch and gkdr/carbons at
shtrom/Lurch4Adium.
Rudimentary tested, needs more.
#65 
Signed-off-by: Olivier Mehani <shtrom@ssji.net>
=> Adium: 50% and testing

_data/clients/miranda_ng.yml
Looking at [#529](https://github.com/miranda-ng/miranda-ng/issues/529) at Miranda NG repo, seems they do have a working version of OMEMO, but things like showing fingerprints are not implemented yet.
This is close to the status Dino folks have, but they are stuck at 67%, when Miranda has 80%. This is probably unreasonable.
=> Fix unreasonable status of Miranda NG

_data/clients/xabber_web.yml
[Xabber Web](https://web.xabber.com) is a relatively new web XMPP client, but it's probably going to rock. :-)
There is a [tracking issue](https://github.com/redsolution/xabber-web/issues/3) on GitHub. The work hasn't been started yet, though.
=> Add Xabber Web to the list

_data/clients/boogie-chat.yml, clients/boogie-chat
@Echolon mentioned in #78 that Boogie Chat isn't visible on the website. I noticed it was put into the wrong directory.
=> Move boogie chat file into the correct directory

_data/clients/bitlbee.yml, _data/clients/boogie-chat.yml, _data/clients/conversations.yml, _data/clients/movim.yml, _data/clients/pidgin.yml, _data/clients/pix-art.yml
Various fixes (naming, WIP status, etc). Movim [does not have any OMEMO-related code](https://github.com/movim/movim/search?q=omemo&type=Commits&utf8=%E2%9C%93), so its status is set to zero.
=> Minor fixes

_data/clients/jsxc.yml, _data/clients/psi.yml, _data/clients/psi_plus.yml
As psi-im/plugins#29 suggests, @stigger is now finished with the plugin. :tada:
A quick checkup of the tracking issues list also shows that JSXC finally [has a working plugin](https://github.com/jsxc/jsxc-plugin-omemo/commit/5e8a59dab895b9a00cb31820978adf7687a2d512). It's still in alpha, though. [Here's the announcement](https://github.com/jsxc/jsxc/issues/228#issuecomment-358628713) by @sualko.
=> Update the status of Psi/Psi+ and JSXC

_data/clients/Kaidan
> Kaidan is a simple, user-friendly Jabber/XMPP client providing a modern user-interface using Kirigami and QtQuick. The back-end of Kaidan is entirely written in C++ using the gloox XMPP client library and Qt 5.
> 
> Currently Kaidan only has been tested on GNU/Linux Desktops, Android & Plasma Mobile, but of course Ubuntu Touch, OS X, iOS and Windows will follow. Of course this is still not everything, i.e. Sailfish OS is missing. To support that we need to wait for a proper QtQuickControls 2 style for it or rewrite the GUI using Silica. Both options are rather unlikely in the near future, so if you want to get a client for Sailfish OS now, maybe take a look at Shmoose, a fork by an earlier developer of Kaidan.
> 
> Kaidan is not finished yet, so don't expect it working as well as a …
=> Added Kadian

_data/clients/conversations.yml, _includes/client_detail.html, _includes/client_row.html, assets/css/style.scss, index.md
This PR will add a new section below the main table that adds a addressable
anchor for every client. Individual details like OS support or plugin /
licensing details can be added down there without cluttering the main table.
Refs #40
Refs #35 
--
@ReneVolution I've taken your PR #85 and split it up into multiple includes.
=> Split up clients into sections with individual anchors #40

index.md
Lurch was published first, and it's also linked in the tracking ticket of pidgin. Also it's maintained, while the libpurble plugin seems to be stalled.
=> the ticket of pidgin links to lurch

_data/clients/xabber.yml
Re-reading https://github.com/redsolution/xabber-android/issues/540 the dev would have legal problems implementing OMEMO, so this likely won't get anywhere.
=> Xabber does not seem to get OMEMO

_data/clients/poezio.yml
dev.louiz.org is not used anymore, we migrated to lab.louiz.org
=> Update poezio’s issue’s URL to the new forge

_data/clients/salut_a_toi.yml
OMEMO is partially implemented in current dev version of Salut à Toi,
and will be fully implemented for stable release.
Fingerprint management and MUC encryption are still missing.
Should be working on BSD, Windows and MacOS, but has not been tested.
Android support is planned, but needs some work, that's the reason of the
WIP after it.
The web support (for Libervia frontend) is not planned for this release,
as it needs more work due to the architecture.
=> [Salut à Toi] updated status

_data/clients/empathy.yml
GNOME migrated from Bugzilla to Gitlab, thus the change of the issue URL
=> empathy: update tracking issue

_data/clients/pidgin.yml
Pidgin's OMEMO functionality is provided by a "highly experimental" plugin and full functionality requires another experimental plugin for Carbons. See https://github.com/bascht/omemo-top/issues/127.
=> Pidgin is not ready

_data/clients/zom.yml
The Zom project switched from XMPP to Matrix, so Zom XMPP has been discontinued
https://github.com/zom/Zom-Android-XMPP
=> Remove Zom IM

_data/clients/poezio.yml
Initial support (encrypting/decrypting messages, publishing bundles) is available in poezio master with the poezio-omemo plugin: https://lab.louiz.org/poezio/poezio-omemo
There is still a lot of work to make it acceptable for secure usage, but at least it can communicate with OMEMO device.
=> Update poezio status

_data/clients/snikket.yml
See https://snikket.org
The client is a Conversations fork.
edit: travis build is failing because 
`zeitwerk-2.2.2 requires ruby version >= 2.4.4, which is incompatible with the current version, ruby 2.4.1p111`
=> Add snikket client

_data/clients/conversations_legacy.yml
Conversations Legacy has been discontinued and taken down from the Play Store
=> Remove "Conversations Legacy"

_data/clients/xabber_web.yml
Xabber Web appears to have implemented OMEMO [1] for both private chats and MUCs, based on commit [2]. Sadly, the version with OMEMO doesn't seem to be released yet, but the `feature/OMEMO` branch has already been merged to their `develop`.
[1]: https://github.com/redsolution/xabber-web/compare/2.1.0...feature/OMEMO
[2]: https://github.com/redsolution/xabber-web/commit/4f1ea6587eb17c83f5e5dab8f70c07acadc02855
=> Set Xabber Web to 100%

_data/clients/tor_messenger.yml
From the project's [wiki](https://gitlab.torproject.org/legacy/trac/-/wikis/doc/TorMessenger): "As of March 2018, Tor Messenger is NO LONGER MAINTAINED and you should NOT use it".
=> Remove unmaintained for a long time TorMessenger

_data/clients/chat-o-matic.yml, _data/clients/renga.yml
There are two promising clients for Haiku: [Renga](https://github.com/HaikuArchives/Renga) and [Chat-O-Matic](https://github.com/JadedCtrl/Chat-O-Matic) (libpurple-based). Sadly, both of them currently don't have OMEMO support.
=> Add Haiku XMPP clients

_data/clients/opa.yml
Old URL died [in 2020](https://github.com/credija/opa/issues/62) (or even earlier) and now redirects to something completely different.
=> Fix Opa's URL

_data/clients/miranda-im.yml
Wayback Machine tells that website stopped working in late 2019.
=> Fix Miranda's URL

_data/clients/eyecu.yml, _data/clients/gajim.yml, _data/clients/irssi.yml, _data/clients/miranda_ng.yml, _data/clients/pidgin.yml, _data/clients/psi_plus.yml
Gajim [works on MacOS, but there is no package yet.](https://gajim.org/download/)
Homepage of irssi-xmpp redirects to GitHub since 2020. Also I think we should specify that it's not irssi itself, but merely a plugin.
=> Small fixes

_data/clients/miranda_ng.yml
Closes #187
I tested latest stable version of Miranda NG (0.95.13.1) with Conversations 2.10.2+fcr. Clients can talk with each other only without encryption, despite OMEMO being enabled in Miranda's settings.
Sending OMEMO message to Miranda NG fails with "I sent you an OMEMO encrypted message but your client doesn’t seem to support that".
Sending it from Miranda NG to Conversations results in "Delivery failure: No valid OMEMO session exists" error.
So apparently [this](https://github.com/miranda-ng/miranda-ng/issues/1255#issuecomment-390143505) is still not resolved.
Given that there's also [no UI](https://github.com/miranda-ng/miranda-ng/issues/1255) for OMEMO in Miranda NG, let's drop it's progress at least to 84%.
=> Fix status of Miranda NG

index.md
From the archived [official repo](https://github.com/fritzy/SleekXMPP): "SleekXMPP is deprecated in favor of Slixmpp, a fork which takes full advantage of Python 3 and asyncio". We have Slixmpp in the Libraries section, so no other changes are needed.
=> SleekXMPP is deprecated

_data/clients/candy.yml
["This project is dead and not maintained anymore".](https://github.com/candy-chat/candy/commit/9ac409e3c1082bf6940b3a0974d6b90b8dcbffdc)
Development [stopped](https://github.com/candy-chat/candy/commits/master) in 2016.
=> Delete dead and unmaintained Candy
